# Generated by Django 5.0.1 on 2024-01-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.CharField(max_length=255),
        ),
    ]
