# Generated by Django 5.0.1 on 2024-01-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
