# Generated by Django 5.0.1 on 2024-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(max_length=255),
        ),
    ]
